### PR TITLE
Add a Remainder method

### PR DESCRIPTION
**Pull request by ghost**
Adds a vectorized remainder method that mirrors the C# implementation (not the IEEE one).
Also adds a `Truncate` method which rounds towards zero unlike the current `Round` method which rounds towards the nearest integer.
This remainder method is an approximation and does not always equal the C# `%`, it is however very close.

TODO:
- [x] Add the method
- [x] Tests?
- [x] Benchmarks

Consider:
- [ ] Add an IEEERemainder?

### CODE REVIEW

**Comment by john-h-k** [comment]
Sounds good to me. Not sure how to implement it at first glance tho. Would recommend looking at DirectXMath source code for inspiration

**Comment by ghost** [comment]
Ready for review.

Current benchmark results:
image

**Comment by john-h-k** [comment]
Can you modify the test to follow the format of the other ones (no output)? And add a little more test data. Some normal inputs, NaN, ±infinity etc

**Comment by ghost** [comment]
Sure, the output was mostly to make sure everything is actually working properly.
I'll also add some more cases.

**Comment by ghost** [comment]
Currently there seems to be issues related to precision which result in weird unexpected results for higher values. I'll have to trace down the actual CLR implementation of `%`.

**Comment by ghost** [comment]
Ready for another review.
Current benchmark results:
```
|    Method |      Mean |     Error |    StdDev |
|---------- |----------:|----------:|----------:|
|    Normal | 67.287 ns | 0.4462 ns | 0.4174 ns |
| MathSharp |  2.729 ns | 0.0411 ns | 0.0384 ns |
```

**Review by john-h-k — APPROVED** [review]
Appears good to me. Reviewing it from my CS class but I think its thorough enough

**Pull request merged**
