### PR TITLE
[WIP] XML Documentation of VectorSingle and VectorDouble

### PR DESCRIPTION
**Pull request by Perksey**

### CODE REVIEW

**Comment by john-h-k** [comment]
@Perksey this still happening?

**Comment by Perksey** [comment]
Ah probably not as it's quite a large job that I am perhaps not too cut out for seeing as I haven't had a lot of time to get to know the library. Perhaps it's best suited for someone else.

You can try and recover what you can from my fork, but I'm throwing in the towel here unfortunately.

**Comment by john-h-k** [comment]
Ay I just meant if it wasnt then undraft the PR and I will merge it lol

**Comment by Perksey** [comment]
Oh haha will do

**Pull request merged**
